version: "3"

services:
  httpd:
    image: nginx:alpine
    volumes:
      - html:/usr/share/nginx/html:ro
    restart: always
    ports:
    - "8180:80"

  app:
    build: .
    volumes:
      - html:/opt/jira-export/www
      - ./data:/opt/jira-export/data

  build:
    build: build
    volumes:
      - .:/srv/www

volumes:
  html:
